require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*

Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - !ruby/regexp /\A *# /

Metrics/BlockLength:
  Exclude:
    - config/environments/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
