require:
  - rubocop-github
  - rubocop-github-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/bundle

Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/FrozenStringLiteralComment:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - !ruby/regexp /\A *# /

Metrics/BlockLength:
  Exclude:
    - config/environments/*
