services:
  web:
    tty: true
    stdin_open: true
    build: .
    working_dir: /app
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && ./bin/dev"
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
  rubygems:
