default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'beautiful_blog_development' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'beautiful_blog_test' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
